source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


link_with ['Either_Target', 'Either_Tests']
target 'Either_Tests', :exclusive => true do
  pod 'Either', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
